
[urgency_low]
    background = "#65A36580"
    foreground = "#CCFFCCE6"
    frame_color = "#65A36503"
    icon = "$HOME/.config/dunst/icons/hyprdots.svg"
    timeout = 5

[urgency_normal]
    background = "#3D6B3A80"
    foreground = "#CFFFCCE6"
    frame_color = "#3D6B3A03"
    icon = "$HOME/.config/dunst/icons/hyprdots.svg"
    timeout = 5
