foreground              #FFFFFF
background              #111510
selection_foreground    #111510
selection_background    #FFFFFF
cursor                  #71856D 
cursor_text_color       #FCFCFC

active_tab_foreground     #111510
active_tab_background     #4B604B
inactive_tab_foreground   #4B604B
inactive_tab_background   #111510

# black
color0      #315229
color8      #628F57

# red
color1      #D5FFCC
color9      #B6F0AA

# green
color2      #CFFFCC
color10     #AFF0AA

# yellow
color3      #CCFFCC
color11     #AAF0AA

# blue
color4      #A9E69A
color12     #A9E69A

# magenta
color5      #9EE69A
color13     #9EE69A

# cyan
color6      #9AE69A
color14     #9AE69A

# white
color7      #D5FFCC
color15     #B6F0AA
