# Ctrl+Shift+C/V for copy/paste in terminal (default)
# Ctrl+C copies if text selected, otherwise sends interrupt
map ctrl+c copy_or_interrupt
map ctrl+v paste_from_clipboard

# Ctrl+Backspace to delete the whole word like Windows
map ctrl+backspace send_text all \x17

# Smooth Cursor Trail Animations
cursor_trail 10
cursor_trail_decay 0.1 0.45
cursor_trail_start_threshold 0

font_size 13.0
