general {{
    col.active_border = rgba({color4.strip}ff) rgba({color2.strip}ff) 45deg
    col.inactive_border = rgba({color1.strip}ff) rgba({color0.strip}ff) 45deg
}}

decoration {{
    shadow {{
        color = rgba({color4.strip}ff)
        color_inactive = rgba({color0.strip}55)
    }}
}}
