exec = gsettings set org.gnome.desktop.interface gtk-theme 'Wallbash-Gtk'
exec = gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'

general {
    col.active_border = rgba(71856Dff) rgba(305229ff) 45deg
    col.inactive_border = rgba(111510ff) rgba(2C3B2Bff) 45deg
}

group {
    col.border_active = rgba(71856Dff) rgba(305229ff) 45deg
    col.border_inactive = rgba(111510cc) rgba(2C3B2Bcc) 45deg
    col.border_locked_active = rgba(FFFFFFff) rgba(FCFCFCff) 45deg
    col.border_locked_inactive = rgba(FFFFFFcc) rgba(FFFFFFcc) 45deg
}
